DELETE http://localhost:3003/api/surfspots/delete
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvcmdlOTFAZ21haWwuY29tIiwiaWQiOiI1ZjI2MDMzNzYyZTNkMzIyMTMzZDM1N2EiLCJpYXQiOjE1OTg4NTgzOTN9.RsNMsFfi-wch-aow-jr5Omfd60_28TTCGIUlz-4d0ds

{
    "ids": ["5f54199b5e635d04a7419c62"]
}